### ISSUE TITLE
.

### ISSUE THREAD

**Issue by simon-hoon** [hunkim/gpt3-python-doc-qa#3]

**Comment by simon-hoon** [comment]
이슈에 익숙하지 않아서 잘못 만들었습니다... ㅠㅠ

**Comment by hunkim** [comment]
[GPT3]
> @simon-hoon 이슈에 익숙하지 않아서 잘못 만들었습니다... ㅠㅠ



난 그 문제에 대해 잘 몰라서 잘못 생각했어... 울음

**Comment by hunkim** [comment]
@simon-hoon 괜찮습니다. 이슈는 만들었다 닫고 하면 됩니다.

**Comment by hunkim** [comment]
[GPT3]
> @hunkim @simon-hoon 괜찮습니다. 이슈는 만들었다 닫고 하면 됩니다.

@simon-hoon 괜찮아. 이슈를 만들고 닫을 수 있습니다.
